[versions]
kotlin = "1.5.10"

android-compile = "30"
android-target = "30"
android-min = "21"

android-gradle = "7.1.0-alpha02"
date-time = "0.2.1"

androidx-appCompat = "1.4.0-alpha02"
androidx-compose = "1.0.0-beta08"
androidx-constraintlayout = "1.0.0-alpha08"
androidx-activity = "1.3.0-beta01"
androidx-navigation = "2.4.0-alpha02"

coroutine = "1.4.2"
hilt = "2.37"
ktor = "1.6.0"
material = "1.4.0-beta01"
squareup-leakcanary = "2.7"
napier = "1.5.0"

testing-assertK = "0.24"
testing-junit = "4.13.2"
testing-opentest = "1.1.1"

plugins-buildkonfig = "0.7.0"
plugins-gradle-versions = "0.38.0"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "date-time" }

androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appCompat" }

androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose" }
androidx-compose-ui-runtime = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-runtime-core = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraintlayout" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

squareup-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "squareup-leakcanary" }
material = { module = "com.google.android.material:material", version.ref = "material" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }

plugins-dependency-check = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "plugins-gradle-versions" }
plugins-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
plugins-buildkonfig = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "plugins-buildkonfig" }

testing-junit = { module = "junit:junit", version.ref = "testing-junit" }
testing-assertK = { module = "com.willowtreeapps.assertk:assertk", version.ref = "testing-assertK" }
testing-opentest = { module = "org.opentest4j:opentest4j", version.ref = "testing-opentest" }
